dist: trusty
sudo: required
language: node_js
notifications:
  email: false
node_js:
  - "8"
install:
  - yarn --frozen-lockfile
script:
  - set -e                     # fail fast
  - yarn test:coverage
  - yarn codecov
